# Sun Aug 9 06:22:42 EDT 2009


include $(MKDIR)/standard.def

###################################################################

target: command.o 

command.o: command.c command.h

###################################################################

# include $(MKDIR)/standard.mk
include $(MKDIR)/hh.mk

